musicio/home/urls.py
from django.urls import path
from . import views
app_name = 'home'

urlpatterns = [
    path('',views.index,name='index'),
    path('register/', views.register, name="register"),
    path('login/',views.login_view,name="login"),
    path('add/',views.add_wish,name='add'),
    path('delete/',views.delete_wish,name='delete'),
    path('logout/',views.logout_profile,name='logout'),
    path('basket/',views.basket,name="basket"),
    path('basket/delete',views.delete_wish_from_basket,name="basket_delete"),
    path('order/',views.order, name="order"),
    path('history/',views.history,name="history"),
    path('publish/',views.publish, name='publish'),
    path('add/song/',views.add_song, name='add_song'),
    path('delete/song/',views.delete_song, name='delete_song'),
    path('publisher/',views.publisher, name='publisher'),
    path('moderator/delete',views.moderator_delete_song,name="mod_delete"),
    path('search/',views.search,name="search")
]

musicio/musicio/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
]

musicio/home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Genre(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

class User(AbstractUser):
    PUBLISHER = 1
    MODERATOR = 2
    USER = 3
    ROLE_CHOICES = (
        (PUBLISHER, 'Publisher'), (MODERATOR, 'Moderator'),(USER,'User')
    )

    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, blank=True, null=True, default=ROLE_CHOICES[2][0])
    pass

class Address(models.Model):
    id = models.AutoField(primary_key=True)
    country = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    house = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=100)
    FK_user = models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True,default=None)

class Publisher(models.Model):
    id = models.AutoField(primary_key=True)
    FK_user = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True,default=None)
    description = models.CharField(max_length=100)

class Moderator(models.Model):
    id = models.AutoField(primary_key=True)
    FK_user = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True,default=None)

class SongInfo(models.Model):
    id = models.AutoField(primary_key=True)
    price = models.FloatField(default=0)
    rating = models.FloatField(default=5)

class Song(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=300,default="Unknown")
    description = models.TextField(max_length=400)
    author = models.CharField(max_length=300,default="Unknown")
    composer = models.CharField(max_length=300,default="Unknown")
    song_url = models.TextField(max_length=1000,default="Not have")
    FK_moderator = models.ForeignKey(Moderator,on_delete=models.CASCADE,blank=True,null=True,default=None)
    FK_genre = models.ForeignKey(Genre,on_delete=models.CASCADE,blank=True,null=True,default=None)
    FK_publisher = models.ForeignKey(Publisher,on_delete=models.CASCADE,blank=True,null=True,default=None)
    FK_song_info = models.ForeignKey(SongInfo,on_delete=models.CASCADE,blank=True,null=True,default=None)
    published = models.BooleanField(default=False)
    DOR = models.DateTimeField(blank=True,auto_now=True)

class Order(models.Model):
    id = models.AutoField(primary_key=True)
    status = models.IntegerField(default=0)

class OrderHistory(models.Model):
    id = models.AutoField(primary_key=True)
    FK_order = models.ForeignKey(Order,on_delete=models.SET_NULL,blank=True,null=True,default=None)
    FK_song = models.ForeignKey(Song,on_delete=models.SET_NULL,blank=True,null=True,default=None)
    FK_user = models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True,default=None)

class Payment(models.Model):
    id = models.AutoField(primary_key=True)
    type_of_payment = models.CharField(max_length=200)
    FK_user = models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True,default=None)

class Basket(models.Model):
    id = models.AutoField(primary_key=True)
    FK_song = models.ForeignKey(Song,on_delete=models.SET_NULL,blank=True,null=True,default=None)
    FK_user = models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True,default=None)
    FK_order =  models.ForeignKey(Order,on_delete=models.SET_NULL,blank=True,null=True,default=None)
    

musicio/home/forms.py
from django import forms
from .models import Genre


class AddSong(forms.Form):
    name = forms.CharField( label="Name")
    composer = forms.CharField(label="Composer")
    author = forms.CharField( label="Author")
    description = forms.CharField(widget=forms.Textarea)
    song_url = forms.CharField(label="Spotify link")
    genre = forms.ChoiceField(choices = [])

    def __init__(self, *args, **kwargs):
        super(AddSong, self).__init__(*args, **kwargs)
        self.fields['genre'].choices = [(x.pk, x.name) for x in Genre.objects.all()]

class SongInfo(forms.Form):
    price = forms.FloatField(label="Price")

class Search(forms.Form):
    item = forms.CharField()

musicio/home/views.py
from django.db import models
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from .models import User, Song, Basket, Order, OrderHistory, Publisher,Genre
from django.apps import apps
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.views.decorators.clickjacking import xframe_options_exempt
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import logout
from .forms import AddSong,SongInfo, Search

@xframe_options_exempt
def index(request):
    current_user = request.user
    id = current_user.id
    if current_user.is_anonymous:
        render(request,'home/index.html',{
            "search": Search()

        })

    elif current_user.role == 1:
        return render(request, 'home/publisher.html', {
            "search": Search()

        })
    elif current_user.role == 2:
        songs = Song.objects.filter(published=0)

        return render(request, 'home/moderator.html', {
            "songs":songs,
            "search": Search()

        })
    baskets = Basket.objects.filter(FK_user=id)
    basket_songs = []
    for basket in baskets:
        basket_songs.append(basket.FK_song.id)
    songs = Song.objects.filter(published=1)
    models = apps.all_models['home']
    return render(request, 'home/index.html', {
            'user': current_user,
            'models': models,
            'songs': songs,
            'baskets': baskets,
            'basket_songs': basket_songs,
            'idd': id,
            "search": Search()
            })


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if (username == "" or email == "" or
            password == "" or confirmation ==""):
            return render(request, "home/register.html", {
                "message": "You have to input all the fields."
            })        
        if password != confirmation:
            return render(request, "home/register.html", {
                "message": "Passwords must match."
            })
        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()   
        except IntegrityError:
            return render(request, "home/register.html", {
                "message": "Username already taken."
            })
        
        login(request, user)
        return HttpResponseRedirect(reverse("home:index"))
    else:
        return render(request, "home/register.html")


def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("home:index"))
        else:
            return render(request, "home/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "home/login.html")


def add_wish(request):
    if (request.method == 'POST' and
            request.user.is_authenticated):
        user = User.objects.get(id=request.POST.get('user'))
        song = Song.objects.get(id=request.POST.get('song'))
        try:
            Basket.objects.get(FK_user=user, FK_song=song)
            return HttpResponseRedirect(reverse('home:index'))
        except Basket.DoesNotExist:
            Basket.objects.create(FK_user=user, FK_song=song).save()
            return HttpResponseRedirect(reverse('home:index'))
    return HttpResponse("You're not logged in")


def delete_wish(request):
    if (request.method == 'POST' and
            request.user.is_authenticated):
        user = User.objects.get(id=request.POST.get('user'))
        song = Song.objects.get(id=request.POST.get('song'))
        Basket.objects.filter(FK_user=user, FK_song=song).delete()
        return HttpResponseRedirect(reverse('home:index'))
    return HttpResponse("You're not logged in")


def delete_wish_from_basket(request):
    if (request.method == 'POST' and
            request.user.is_authenticated):
        user = User.objects.get(id=request.POST.get('user'))
        song = Song.objects.get(id=request.POST.get('song'))
        Basket.objects.filter(FK_user=user, FK_song=song).delete()
        return HttpResponseRedirect(reverse('home:basket'))
    return HttpResponse("You're not logged in")


def logout_profile(request):
    logout(request)
    return HttpResponseRedirect(reverse('home:index'))


def basket(request):
    sum = 0
    basket_items = Basket.objects.filter(FK_user=request.user)
    for basket_item in basket_items:
        sum += basket_item.FK_song.FK_song_info.price
    return render(request, 'home/basket.html', {
        "basket_items": basket_items,
        "sum": sum,
    })


def order(request):
    if (request.method == 'POST' and
            request.user.is_authenticated):
        order_item = Order.objects.create()
        order_item.status = 1
        order_item.save()
        basket_items = Basket.objects.filter(FK_user=request.user)
        basket_items.update(FK_order=order_item)
        for basket_item in basket_items:
            order = OrderHistory.objects.create(
                FK_user=request.user, FK_order=order_item, FK_song=basket_item.FK_song)
        basket_items.delete()
        return HttpResponseRedirect(reverse('home:basket'))
    return HttpResponse("works")


def history(request):
    orders = OrderHistory.objects.filter(FK_user=request.user)
    return render(request, 'home/history.html', {
        "orders": orders,
    })


def publish(request):
    if (request.method == "POST" and 
        request.user.is_authenticated):
        song = Song.objects.get(id=request.POST.get('song'))
        song.published = True
        song.save()
        return HttpResponseRedirect(reverse('home:index'))
    return HttpResponse("Yra")

def add_song(request):
    if (request.method == "POST" and
        request.user.role == 1):
            form = AddSong(request.POST)
            if form.is_valid():
                begin = "src= "
                end = " width=700 height=90 frameborder=0 allowtransparency=true allow=encrypted-media"
                url_link = form.cleaned_data["song_url"]
                name = form.cleaned_data["name"]
                composer = form.cleaned_data["composer"]
                author = form.cleaned_data['author']
                description = form.cleaned_data['description']
                genre = form.cleaned_data['genre']
                song_url = begin + url_link + end
                publisher = request.user.id
                publisher = Publisher.objects.get(FK_user=User.objects.get(id=request.user.id))
                Song.objects.create(name=name,description=description,author=author, composer=composer,song_url=song_url,FK_publisher=publisher).save()
                return HttpResponseRedirect(reverse('home:index'))
            else:
                return HttpResponse(form.is_valid())
    return render(request,'home/add.html',{
        "form": AddSong(),
        "form_price": SongInfo(),

    })

def publisher(request):
    user = User.objects.get(id=request.user.id)
    publisher = Publisher.objects.get(FK_user=user)
    songs = Song.objects.filter(FK_publisher=publisher)
    return render(request,'home/publisher.html',{
        "songs" : songs,
        "user":user,
        "publisher":publisher
    })

def delete_song(request):
    if (request.user.role == 1 or
    request.user.role == 2):
        if request.method == "POST":
            song = Song.objects.filter(id=request.POST.get('song')).delete()
            return HttpResponseRedirect(reverse('home:index'))
        else:
            user = User.objects.get(id=request.user.id)
            list_of_songs = Song.objects.filter(FK_publisher=Publisher.objects.get(FK_user=user))
            return render(request, 'home/delete.html', {
                "songs":list_of_songs,
            }) 
def search(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = Search(request.POST)
        # check whether it's valid:
        if form.is_valid():
            item = form.cleaned_data['item']
            return render(request,'home/search.html',{
                "songs":Song.objects.filter(name__contains=item)
                })

    return HttpResponseRedirect(reverse('home:index'))


def moderator_delete_song(request):
    if request.user.role == 2:
        if request.method == "POST":
            Song.objects.filter(id=request.POST.get('song')).delete()
        else:
            songs = Song.objects.all()
            return render(request, 'home/delete.html',{
                "songs":songs
            })
    pass

musicio/home/templates/home/add.html
{% extends 'home/layout.html' %}

{% block body %}
<form action="{% url 'home:add_song' %}" method="POST">
    {% csrf_token %}
    {{form.as_ul}}
    {{form_price}}
    <hr>
    <input type="submit" class="btn btn-dark" value="Add a Song">
    <br>
    <hr>
</form>
{% endblock%}

musicio/home/templates/home/basket.html
{% extends "home/layout.html" %}



{% block body %}
{% if basket_items.count == 0 %}
<h4>No items in a basket</h4>
{% else %}
<div class="songs-container">

{% for basket_item in basket_items %}
<div class="song-container">
<hr>
<h3>{{ basket_item.FK_song.name }} </h3> 
<iframe {{basket_item.FK_song.song_url}}> </iframe>

<p>{{ basket_item.FK_song.description }} 

    <form action="{% url 'home:basket_delete' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" value="{{basket_item.FK_song.id}}" name="song">
        <input type="hidden" value="{{user.id}}" name="user">
        <button type="Submit" class="btn btn-danger">-</button>
    </form>
<h5>{{ basket_item.FK_song.FK_song_info.price }} $
</h5>
</p>

    <hr>
</div>
    {% endfor %}
    <form action="{% url 'home:order' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" value="{{basket_items}}" name="basket_items">
        <button type="Submit" class="btn btn-dark">Order</button>
    </form>    
<h4>Final price: ${{sum}} </h4>
</div>
{% endif %}
{% endblock %}

musicio/home/templates/home/delete.html
{% extends 'home/layout.html' %}
{% block body %}
<hr>
{% for song in songs %}
<div class="song-container">
<iframe {{song.song_url}}></iframe>
<br>
    {{song.name}}
    {{song.description}}
    <form action="{% url 'home:delete_song' %}" method="post">
        {%csrf_token%}
        <input type="hidden" name="song" value={{song.id}}>
        <input type="submit" class="btn btn-dark" value="Delete">
    </form>
    <hr>
</div>
{% endfor %}
{% endblock %}

musicio/home/templates/home/history.html
{% extends 'home/layout.html' %}


{% block body%}
    {% for order in orders%}
    <h4>{{order.FK_song.name}}</h4>
    <iframe {{order.FK_song.song_url}}> </iframe>

    {% endfor %}
{% endblock %}

musicio/home/templates/home/index.html
{% extends 'home/layout.html' %}

{% block search %}
<form action="{% url 'home:search' %}" method="post">
    {% csrf_token %}
{{search}}
<input type="submit" value="Search">
</form>
{% endblock %}
{% block body %}
<h1>Songs</h1>
<hr />
<div class="songs-container">

{% for song in songs %}
<div class="song-container">
<hr class="song_lines" />
<iframe {{song.song_url}}> </iframe>
{% if song.id in basket_songs %}
<form action="{% url 'home:delete' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" value="{{song.id}}" name="song" />
    <input type="hidden" value="{{user.id}}" name="user" />
    <button type="Submit" class="btn btn-dark">Delete from basket</button>
</form>
<br />

<h3>{{song.name}}</h3>
{{song.description}}
<h6>${{song.FK_song_info.price}}</h6>
<hr class="song_lines" />
</div>
{% else %}
<div class="song-container">
<form action="{% url 'home:add' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" value="{{song.id}}" name="song" />
    <input type="hidden" value="{{user.id}}" name="user" />
    <button type="Submit" class="btn btn-dark">Add to Basket</button>
</form>
<br />
<h3>{{song.name}}</h3>
{{song.description}}
<h6>${{song.FK_song_info.price}}</h6>
<hr class="song_lines" />
</div>
{% endif %} {% endfor %}
</div>

{% endblock body %}

musicio/home/templates/home/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'home/style.css' %}">

    </head>

<body>

    {% block nav %}
    <div class="top-nav">
    {% if user.role == 3 %}
    <a href="{% url 'home:index' %}" class="btn btn-warning"> Home </a>
    <a href="{% url 'home:basket' %}" class="btn btn-warning"> Basket </a>
    <a href="{% url 'home:history' %}" class="btn btn-warning"> Order History </a>
    <a href="{% url 'home:index' %}" class="btn btn-warning"> User </a>
    {% endif %}

    {% if user.role == 2 %}

    <a href="{% url 'home:index' %}" class="btn btn-warning"> Home moderator</a>
    <a href="{% url 'home:mod_delete' %}" class="btn btn-warning"> Delete a song</a>
    
    {% endif %}   

    {% if user.role == 1 %}
    <a href="{% url 'home:publisher' %}" class="btn btn-warning"> Home publisher</a>
    <a href="{% url 'home:add_song' %}" class="btn btn-warning"> Add a song</a>
    <a href="{% url 'home:delete_song' %}" class="btn btn-warning"> Delete a song</a>
    {% endif %}
    </div>
    {% endblock %}
    {% block search %}
    <br>
        <form action="{% url 'home:search' %}" method="post" class = "search">
            {% csrf_token %}
            <input type="text" name="search" id="">
            <input type="submit" value="Search">
        </form>
    <br>
    {% endblock %}
    {% block body %}
    {% endblock %}

    {% block bottom %}
    {% if user.is_authenticated %}
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home:logout' %}">Log out</a>
        </li>
    </ul>

    {% else %}
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home:login' %}">Log In</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home:register' %}">Register</a>
        </li>
    </ul>
    {% endif %}
    {% endblock %}
</body>

</html>

musicio/home/templates/home/login.html
{% extends "home/layout.html" %}

{% block search %}

{% endblock%}

{% block body %}

    <h2>Login</h2>


    <form action="{% url 'home:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'home:register' %}">Register here.</a>

{% endblock %}

musicio/home/templates/home/moderator.html
{% extends 'home/layout.html' %}

{% block body %}
<br>
<hr>
{% if user.role == 2 %}
<div class="songs-container">
{% for song in songs %}
<div class="song-container">
    
    <iframe {{song.song_url}}></iframe>
    <form action="{% url 'home:publish' %}" method="POST" id="left">
        {% csrf_token %}
        <input type="hidden" value="{{song.id}}" name="song" />
        <button type="Submit" class="btn btn-dark">Publish</button>
    </form>
    <br>
    <form action="{% url 'home:delete_song' %}" method="post" >
        {% csrf_token %}
        <input type="hidden" value="{{song.id}}" name="song" />
        <button type="Submit" class="btn btn-dark" id="right">Remove</button>
    </form>
    <br>
    <h3>{{song.name}}</h3>
    <hr>
</div>
    {% endfor %}
</div>
    {% endif %}
{% endblock %}

musicio/home/templates/home/publisher.html
{% extends 'home/layout.html' %}

{% block body %}

<div class="songs-container">
{% for song in songs %}
<div class="song-container">
    <hr>
    <iframe {{song.song_url}}> </iframe>
    <p>
    <h6>{{song.name}}</h6>
    <h6>{{song.description}}</h6>
    </p>
    <hr>
</div>
{% endfor %}
</div>
{% endblock %}

musicio/home/templates/home/register.html
{% extends "home/layout.html" %}

{% block search %}

{% endblock %}

{% block body %}

    <h2>Register</h2>
    {{message}}
    <form action="{% url 'home:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'home:login' %}">Log In here.</a>

{% endblock %}

musicio/home/templates/home/search.html
{% extends 'home/layout.html' %}
{% block body %}

<div class="songs-container">
    {{item}}
    {{genre}}
{% for song in songs %}
    <div class="song-container">
        <iframe {{song.song_url}}></iframe>
        <br>
        {{song.name}}
        <br>
        {{song.description}}
        <br>
        {{song.author}}

    </div>
{% endfor %}
</div>
{% endblock %}